trigger:
- main

pool:
  name: todopull

variables:
- name: GITHUB_TOKEN
  readonly: true

jobs:
- job: SyncRepos
  pool:
    name: todopull

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      git clone https://github.com/dockersamples/todo-list-app.git
      cd todo-list-app
      git checkout main
    displayName: 'Checkout source repo'

  - script: |
      git config --global user.name '$(GITHUB_USERNAME)'
      git config --global user.email 'you@example.com'
      git clone https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@github.com/nabeelshafqat19/to-do-list-from-git.git
      cd to-do-list-from-git
      xcopy ..\todo-list-app\* . /s /e /y
      git add .
      git commit -m "Sync from source repository"
      git push https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@github.com/nabeelshafqat19/to-do-list-from-git.git
    displayName: 'Push to target repo'